# Generated by Django 3.2 on 2022-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(blank=True, choices=[('movie', 'movie'), ('tv_show', 'tv show')], max_length=50,
                                   null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(blank=True,
                                   choices=[('actor', 'actor'), ('writer', 'writer'), ('director', 'director')],
                                   max_length=50, null=True, verbose_name='role'),
        ),
    ]
