# Generated by Django 3.2 on 2026-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220726_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv_show', 'tv show')], default='movie', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
    ]
